---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki-pvc
spec:
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: snapshotToReplace
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
